from .catch_error import catch_exception

__all__ = ["catch_exception"]
